# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: App\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.behat.context.ui.backend.notification:
        class: App\Behat\Context\Ui\Backend\NotificationContext
        arguments:
            - "@app.behat.notification_checker"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.frontend.homepage:
        class: App\Behat\Context\Ui\Frontend\HomepageContext
        arguments:
            - "@app.behat.page.frontend.home"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.frontend.login:
        class: App\Behat\Context\Ui\Frontend\LoginContext
        arguments:
            - "@app.behat.page.frontend.home"
            - "@app.behat.page.frontend.account.login"
            - "@app.behat.page.frontend.account.register"
            - "@app.behat.page.frontend.account.request_password_reset"
            - "@app.behat.page.frontend.account.reset_password"
            - "@app.behat.notification_checker"
            - "@app.behat.current_page_resolver"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.frontend.managing_bookmarks:
        class: App\Behat\Context\Ui\Frontend\ManagingBookmarksContext
        arguments:
            - "@app.behat.page.frontend.bookmark.create_video"
            - "@app.behat.page.frontend.bookmark.create_photo"
            - "@app.behat.page.frontend.bookmark.index"
            - "@app.behat.page.frontend.bookmark.update"
            - "@app.behat.current_page_resolver"
        tags:
        - { name: fob.context_service }

    app.behat.context.ui.frontend.notification:
        class: App\Behat\Context\Ui\Frontend\NotificationContext
        arguments:
            - "@app.behat.notification_checker"
        tags:
            - { name: fob.context_service }

    app.behat.context.ui.email:
        class: App\Behat\Context\Ui\EmailContext
        arguments:
            - "@app.behat.shared_storage"
            - "@app.behat.email_checker"
        tags:
            - { name: fob.context_service }
