services:
    # default configuration for services in *this* file
    _defaults:
        autoconfigure: true

    command_handlers:
        namespace: App\Command\
        resource: '../../src/Command/*'
        tags: [command_handler]

    sylius.controller.security:
        class: Sylius\Bundle\UiBundle\Controller\SecurityController
        public: true
        arguments:
            - "@security.authentication_utils"
            - "@form.factory"
            - "@templating.engine.twig"
            - "@security.authorization_checker"
            - "@router"
