services:
    app.fixture.bookmark:
        class: App\Fixture\BookmarkFixture
        arguments:
            - "@app.manager.bookmark"
            - "@app.fixture.example_factory.bookmark"
        tags:
            - { name: sylius_fixtures.fixture }
