# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
     sylius.form.type.admin_user.validation_groups: ["sylius"]

services:
    App\Form\Type\BookmarkType:
        arguments:
            - '%app.model.bookmark.class%'
            - [video, photo]
        tags:
            - { name: form.type }

    app.date_type_extension:
        class: App\Form\Extension\DateTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\DateType }
