eight_points_guzzle:
    clients:
        flickr:
            # Write here the host where to do requests
            base_url: "https://www.flickr.com"
        vimeo:
           base_url: "https://vimeo.com"
