sylius_resource:
    resources:
        app.bookmark:
            classes:
                model: App\Entity\Bookmark
                form: App\Form\Type\BookmarkType
        app.oauth_client:
            classes:
                model: App\Entity\OAuth\Client
