# This file is part of the Sylius package.
# (c) Paweł Jędrzejewski

sylius_fixtures:
    suites:
        default:
            listeners:
                orm_purger: ~
                logger: ~

            fixtures:
                bookmark:
                    options:
                        random: 20
                        custom:
                            -
                                type: video
                                title: Star Wars
                                author_name: George Lucas
                                tags:
                                    - movie
                                    - science fiction
                                    - space battle
                                added_at: today
