app_frontend_homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_frontend_bookmark_index

app_frontend_bookmark:
    resource: "frontend/bookmark.yml"
