app_frontend_homepage:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: app_frontend_bookmark_index
        permanent: true

app_frontend_account:
    resource: "frontend/account.yml"
    prefix: "mon-compte"

app_frontend_bookmark:
    resource: "frontend/bookmark.yml"

sylius_security:
    resource: "frontend/security.yml"

app_frontend_partial:
    resource: "frontend/partial.yml"
    prefix: "/_partial"
