# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    #    service_name:
    #        class: App\Directory\ClassName
    #        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    app.behat.page.frontend.bookmark.create:
        class: App\Behat\Page\Frontend\Bookmark\CreatePage
        parent: app.behat.page.frontend.crud.create
        public: false
        arguments: ["app_frontend_bookmark_create"]

    app.behat.page.frontend.bookmark.index:
        class: App\Behat\Page\Frontend\Bookmark\IndexPage
        parent: app.behat.page.frontend.crud.index
        public: false
        arguments: ["app_frontend_bookmark_index"]

    app.behat.page.frontend.bookmark.update:
        class: App\Behat\Page\Frontend\Bookmark\UpdatePage
        parent: app.behat.page.frontend.crud.update
        public: false
        arguments: ["app_frontend_bookmark_update"]