app_frontend_bookmark:
    resource: |
        alias: app.bookmark
        section: frontend
        except: ['show']
        redirect: update
        grid: app_frontend_bookmark
        vars:
            all:
                subheader: app.ui.manage_bookmarks
                templates:
                    form: frontend/bookmark/_form.html.twig
            index:
                icon: bookmark
        templates: frontend/crud
    type: sylius.resource
