app_frontend_login:
    path: /login
    methods: [GET]
    defaults:
        _controller: sylius.controller.security:loginAction
        _sylius:
            template: frontend/security/login.html.twig


app_frontend_user_check_action:
    path: /user-check
    methods: [GET]
    defaults:
        _controller: sylius.controller.app_user:showAction
        _format: json
        _sylius:
            repository:
                method: findOneByEmail
                arguments:
                    email: $email
            serialization_groups: [Secured]

app_frontend_user_request_verification_token:
    path: /verify
    methods: [POST]
    defaults:
        _controller: sylius.controller.app_user:requestVerificationTokenAction

app_frontend_user_verification:
    path: /verify/{token}
    methods: [GET]
    defaults:
        _controller: sylius.controller.app_user:verifyAction
        _sylius:
            redirect: app_frontend_homepage