#!/usr/bin/env bash

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../../../../bash/common.lib.sh"

print_header "Validating (Coding standards)" "BookmarkIt"
run_command "vendor/bin/php-cs-fixer fix src --dry-run --diff --show-progress=dots"
