# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'fileutils'

VAGRANTFILE_API_VERSION = "2"

APT_CACHE_DIRECTORY = File.expand_path('~/dev/debianLocalCache')

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.define :bookmark_it do |bookmark_it_config|
        bookmark_it_config.vm.box = "debian/jessie64"

        bookmark_it_config.vm.provider "virtualbox" do |v|
            v.gui = false
            v.memory = 1024
            v.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root", "1"]
        end

        bookmark_it_config.vm.synced_folder "./../../", "/var/www/bookmark_it", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'nolock', 'actimeo=2']

        if File.exists? APT_CACHE_DIRECTORY then
            bookmark_it_config.vm.synced_folder APT_CACHE_DIRECTORY, "/home/mobizel/aptCacheDirectory", type: "nfs", mount_options: ['rw', 'vers=3', 'tcp', 'fsc', 'nolock', 'actimeo=2']
        end

        bookmark_it_config.vm.network "private_network", ip: "10.0.0.200"
        if (ENV['MBZ_PROJ_ID'] != nil) then
            bookmark_it_config.vm.network "forwarded_port", guest: 80, host: ("8" + ENV['MBZ_PROJ_ID']).to_i
            bookmark_it_config.vm.network "forwarded_port", guest: 22, host: ("22" + ENV['MBZ_PROJ_ID']).to_i
        end

        # Shell provisioning
        bookmark_it_config.vm.provision :shell, :path => "shell_provisioner/run.sh"
        bookmark_it_config.vm.provision :shell, privileged: false, path: "shell_provisioner/module/app.sh"

        bookmark_it_config.vm.provision :shell, privileged: false, inline: <<-EOF
          echo "Virtual machine provisioned and started"
        EOF
    end
end
